/** @type {import('tailwindcss').Config} */
export default {
  prefix: 'plm-',
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['"DM Sans"', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'card-flip': {
          '0%': { transform: 'rotateY(180deg) scale(0.8)', opacity: '0' },
          '60%': { transform: 'rotateY(0deg) scale(1.05)', opacity: '1' },
          '100%': { transform: 'rotateY(0deg) scale(1)', opacity: '1' },
        },
        'card-shine': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'pack-shake': {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '10%': { transform: 'rotate(-3deg)' },
          '20%': { transform: 'rotate(3deg)' },
          '30%': { transform: 'rotate(-3deg)' },
          '40%': { transform: 'rotate(3deg)' },
          '50%': { transform: 'rotate(-2deg)' },
          '60%': { transform: 'rotate(2deg)' },
          '70%': { transform: 'rotate(-1deg)' },
          '80%': { transform: 'rotate(1deg)' },
          '90%': { transform: 'rotate(0deg)' },
        },
        'pack-burst': {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.15)', opacity: '0.8' },
          '100%': { transform: 'scale(0)', opacity: '0' },
        },
        'card-enter': {
          '0%': { transform: 'translateY(100%) scale(0.5)', opacity: '0' },
          '70%': { transform: 'translateY(-5%) scale(1.02)', opacity: '1' },
          '100%': { transform: 'translateY(0) scale(1)', opacity: '1' },
        },
        'shimmer': {
          '0%': { left: '-100%' },
          '100%': { left: '200%' },
        },
        'border-shimmer': {
          '0%, 100%': { boxShadow: '0 0 6px rgba(255,215,0,0.4), 0 0 0 3px rgba(255,215,0,0.5), inset 0 0 6px rgba(255,215,0,0.1)' },
          '50%': { boxShadow: '0 0 20px rgba(255,200,0,0.9), 0 0 0 3px rgba(255,230,50,0.95), inset 0 0 12px rgba(255,215,0,0.3)' },
        },
        'screen-shake': {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '10%': { transform: 'translate(-3px, -2px)' },
          '20%': { transform: 'translate(3px, 1px)' },
          '30%': { transform: 'translate(-2px, 3px)' },
          '40%': { transform: 'translate(2px, -1px)' },
          '50%': { transform: 'translate(-1px, 2px)' },
          '60%': { transform: 'translate(1px, -2px)' },
          '70%': { transform: 'translate(-1px, 1px)' },
          '80%': { transform: 'translate(1px, -1px)' },
          '90%': { transform: 'translate(0, 1px)' },
        },
        'particle-burst': {
          '0%': { opacity: '1', transform: 'scale(1) translate(0, 0)' },
          '100%': { opacity: '0', transform: 'scale(0.3) translate(var(--tx, 50px), var(--ty, -80px))' },
        },
        'confetti-fall': {
          '0%': { transform: 'translateY(-20px) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateY(110vh) rotate(720deg)', opacity: '0' },
        },
        'sparkle-pulse': {
          '0%, 100%': { opacity: '0.4', transform: 'scale(0.8)' },
          '50%': { opacity: '1', transform: 'scale(1.2)' },
        },
        'stamp-in': {
          '0%': { opacity: '0', transform: 'scale(3) rotate(-18deg)' },
          '55%': { opacity: '1', transform: 'scale(0.88) rotate(3deg)' },
          '80%': { transform: 'scale(1.04) rotate(-1deg)' },
          '100%': { opacity: '1', transform: 'scale(1) rotate(0deg)' },
        },
        'name-write': {
          '0%': { clipPath: 'inset(0 100% 0 0)' },
          '100%': { clipPath: 'inset(0 0 0 0)' },
        },
        'twinkle-star': {
          '0%, 100%': { opacity: '1', transform: 'scale(1) rotate(0deg)', filter: 'drop-shadow(0 0 3px #FFD700)' },
          '50%': { opacity: '0.55', transform: 'scale(1.25) rotate(18deg)', filter: 'drop-shadow(0 0 10px #FFD700)' },
        },
        'stat-glow': {
          '0%, 100%': { boxShadow: '0 2px 6px rgba(0,0,0,0.2), 0 0 6px rgba(157,23,77,0.5)' },
          '50%': { boxShadow: '0 2px 6px rgba(0,0,0,0.2), 0 0 16px rgba(157,23,77,1), 0 0 24px rgba(194,24,91,0.7)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-out',
        'slide-up': 'slide-up 0.3s ease-out',
        'card-flip': 'card-flip 0.6s ease-out forwards',
        'card-shine': 'card-shine 2s linear infinite',
        'pack-shake': 'pack-shake 0.8s ease-in-out',
        'pack-burst': 'pack-burst 0.4s ease-out forwards',
        'card-enter': 'card-enter 0.5s ease-out forwards',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
        'border-shimmer': 'border-shimmer 2s ease-in-out infinite',
        'screen-shake': 'screen-shake 0.4s ease-out',
        'particle-burst': 'particle-burst 1s ease-out forwards',
        'confetti-fall': 'confetti-fall var(--duration, 3s) ease-in var(--delay, 0s) forwards',
        'sparkle-pulse': 'sparkle-pulse 1.2s ease-in-out infinite',
        'stamp-in': 'stamp-in 0.6s cubic-bezier(.2,.8,.3,1.2) forwards',
        'name-write': 'name-write 0.9s ease-out forwards',
        'twinkle-star': 'twinkle-star 1.8s ease-in-out infinite',
        'stat-glow': 'stat-glow 1.5s ease-in-out infinite',
      },
      colors: {
        cream: '#FAF8F5',
        charcoal: '#1A1A1A',
        'charcoal-light': '#2D2D2D',
        warm: {
          50: '#FDFCFB',
          100: '#FAF8F5',
          200: '#F0EDE8',
          300: '#E0DCD5',
          400: '#C4BFB6',
          500: '#9E9A93',
          600: '#6B6760',
          700: '#4A4640',
          800: '#2D2A26',
          900: '#1A1A1A',
        },
      },
    },
  },
  plugins: [],
}
