/**
 * Modifier-effects layer.
 *
 * Events generated by /src/engine/events.ts emit ActiveModifier objects with
 * effects like `{ TSS: 2 }`, `{ DEV_BONUS: 1 }`, `{ TSS_HOME: 1 }`,
 * `{ FORMATION_DOUBLE: 1 }`, `{ DERBY_CHAOS: 2 }`, etc. Until now, none of
 * those keys were read by the match or aging engines — the modifiers existed
 * in state but never reached the simulation. This file is the bridge:
 *
 *   - `computeTeamModifiers`   → team-wide TSS effects (TSS, TSS_HOME,
 *                                 TSS_UNDERDOG, DERBY_CHAOS, FORMATION_DOUBLE)
 *   - `getEffectivePlayer`     → per-player stat/form overrides
 *                                 (ATK, DEF, MOV, PWR, MEN, SKL, FORM)
 *   - `computeAgingModifiers`  → aging-time effects (DEV_BONUS, YOUTH_BOOST)
 *
 * Modifiers carry an optional `targetClubId`; effects only apply to that
 * club. Player-level modifiers additionally carry `targetPlayerId`.
 */

import type { ActiveModifier, Player, PlayerStats } from '@/types/entities';
import { calculateOverall } from './playerGen';

export interface TeamModifiers {
  /** Direct flat addition to TSS (squad-morale-high TSS:+2, team-bonding TSS:+1, …). */
  tssBonus: number;
  /** Added only when the club is playing at home. */
  tssHomeBonus: number;
  /** Added only when the club's pre-modifier TSS is lower than the opponent's. */
  tssUnderdogBonus: number;
  /** Adds to the derby chaos cap, only in derby matches. */
  derbyChaosBonus: number;
  /** If true, the formation modifier on TSS is doubled (new-tactics breakthrough). */
  formationDoubleActive: boolean;
  /** Squad-wide form shift (e.g. international break FORM:-1) applied to avg form. */
  squadFormShift: number;
}

export const EMPTY_TEAM_MODS: TeamModifiers = {
  tssBonus: 0,
  tssHomeBonus: 0,
  tssUnderdogBonus: 0,
  derbyChaosBonus: 0,
  formationDoubleActive: false,
  squadFormShift: 0,
};

/**
 * Aggregate squad-wide modifiers that apply to a given clubId.
 * Player-targeted modifiers are excluded — those flow through `getEffectivePlayer`.
 */
export function computeTeamModifiers(
  modifiers: ActiveModifier[] | undefined,
  clubId: string,
): TeamModifiers {
  if (!modifiers || modifiers.length === 0) return { ...EMPTY_TEAM_MODS };
  const out: TeamModifiers = { ...EMPTY_TEAM_MODS };

  for (const mod of modifiers) {
    if (mod.targetClubId !== clubId) continue;
    if (mod.targetPlayerId) continue; // per-player mods handled separately
    const e = mod.effect || {};
    if (typeof e.TSS === 'number') out.tssBonus += e.TSS;
    if (typeof e.TSS_HOME === 'number') out.tssHomeBonus += e.TSS_HOME;
    if (typeof e.TSS_UNDERDOG === 'number') out.tssUnderdogBonus += e.TSS_UNDERDOG;
    if (typeof e.DERBY_CHAOS === 'number') out.derbyChaosBonus += e.DERBY_CHAOS;
    if (typeof e.FORMATION_DOUBLE === 'number' && e.FORMATION_DOUBLE > 0) {
      out.formationDoubleActive = true;
    }
    if (typeof e.FORM === 'number') out.squadFormShift += e.FORM;
  }

  return out;
}

const STAT_KEYS: (keyof PlayerStats)[] = ['ATK', 'DEF', 'MOV', 'PWR', 'MEN', 'SKL'];

/**
 * Return a shallow copy of the player with effective stats, overall, and form
 * after applying any active modifiers that target them (or their club via a
 * club-wide stat mod). The original player object is left untouched.
 *
 * Stats are clamped to [1, 99]; form to [-5, 5].
 *
 * Note: this re-derives overall via calculateOverall(position) so a +4 ATK on
 * a striker actually moves the TSS calculation. Without re-derivation, the
 * baseRating (which reads player.overall) would ignore the boost entirely.
 */
export function getEffectivePlayer(
  player: Player,
  modifiers: ActiveModifier[] | undefined,
  clubId: string,
): Player {
  if (!modifiers || modifiers.length === 0) return player;

  let statDeltas: Partial<Record<keyof PlayerStats, number>> | null = null;
  let formDelta = 0;
  let touched = false;

  for (const mod of modifiers) {
    if (mod.targetClubId !== clubId) continue;
    // Per-player mod must match the player; club-wide stat mod (no playerId)
    // applies if the player belongs to the club.
    if (mod.targetPlayerId && mod.targetPlayerId !== player.id) continue;
    const e = mod.effect || {};

    for (const k of STAT_KEYS) {
      const v = e[k];
      if (typeof v === 'number' && v !== 0) {
        statDeltas = statDeltas || {};
        statDeltas[k] = (statDeltas[k] || 0) + v;
        touched = true;
      }
    }
    if (typeof e.FORM === 'number') {
      formDelta += e.FORM;
      touched = true;
    }
  }

  if (!touched) return player;

  const newStats: PlayerStats = { ...player.stats };
  if (statDeltas) {
    for (const k of STAT_KEYS) {
      const d = statDeltas[k];
      if (typeof d === 'number' && d !== 0) {
        newStats[k] = Math.max(1, Math.min(99, newStats[k] + d));
      }
    }
  }

  const newOverall = statDeltas
    ? calculateOverall(newStats, player.position)
    : player.overall;
  const newForm = formDelta
    ? Math.max(-5, Math.min(5, (player.form ?? 0) + formDelta))
    : player.form;

  return { ...player, stats: newStats, overall: newOverall, form: newForm };
}

export interface AgingModifiers {
  /** Boosts season-end development stat changes for the player's club. */
  devBonus: number;
  /** Boosts regen + youth-intake ratings for the player's club. */
  youthBoost: number;
}

export const EMPTY_AGING_MODS: AgingModifiers = { devBonus: 0, youthBoost: 0 };

/**
 * Aggregate season-long aging-related modifiers that apply to a clubId.
 * Read by App.tsx season-end aging flow.
 */
export function computeAgingModifiers(
  modifiers: ActiveModifier[] | undefined,
  clubId: string,
): AgingModifiers {
  if (!modifiers || modifiers.length === 0) return { ...EMPTY_AGING_MODS };
  const out: AgingModifiers = { ...EMPTY_AGING_MODS };
  for (const mod of modifiers) {
    if (mod.targetClubId !== clubId) continue;
    const e = mod.effect || {};
    if (typeof e.DEV_BONUS === 'number') out.devBonus += e.DEV_BONUS;
    if (typeof e.YOUTH_BOOST === 'number') out.youthBoost += e.YOUTH_BOOST;
  }
  return out;
}
